### PR TITLE
Enable component lookup

### PR DESCRIPTION
**Pull request by zzarcon**
This enables component lookup, based on your commented code:

```javascript
Devtools.component("ember1234", "user-avatar");
```

Hope you like it ^^

### CODE REVIEW

**Comment by aexmachina** [comment]
Aha, very good! I didn't see how to do that and had to move on. Thanks!

Would you mind adding tests please?

**Comment by zzarcon** [comment]
@aexmachina done!

I fixed the commented tests that matches with my component proposal. If you want we can fix the other ones, but I'm not sure if I agree 100% with their approach hehe. 

Anyway, I think we can fix the other ones later, when the method supports their functionality. What do you think? :dancers:

**Comment by aexmachina** [comment]
Okay great, thanks. Not sure what you're referring to (I didn't write those tests), but I'm okay with your suggestion.

**Comment by aexmachina** [comment]
Published v4.2.0

**Comment by zzarcon** [comment]
Oh sorry, I thought you wrote this tests https://github.com/aexmachina/ember-devtools/blob/master/tests/acceptance/devtools-test.js#L111-L154 ^^

**Comment by aexmachina** [comment]
Nope, several people have contributed to this module over the years.

**Comment by aexmachina** [comment]
Any ideas on this @zzarcon? It's still not supported, I think I'll remove the methods again.

**Comment by zzarcon** [comment]
@aexmachina yeah sorry, I don't know how to fix it... we can remove it for now, will be better.

**Pull request merged**
