### PR TITLE
Log render duration

### PR DESCRIPTION
**Pull request by zzarcon**
Allows the developer to see the rendering duration ^^

Thanks for the repo and hope you find this useful!

### CODE REVIEW

**Comment by aexmachina** [comment]
Nice, just need to add tests and docs to README.md and I'll merge.

**Comment by zzarcon** [comment]
@aexmachina not quite sure how to add tests to this feature, can you help me? :)

**Comment by zzarcon** [comment]
@aexmachina i just added some tests to check the number of times a component get rendered. Hope that the tests are valid for you ^^

Thanks!

**Comment by aexmachina** [comment]
Cool, thanks. That's sufficient. Would you mind also adding an entry to README as well?

**Comment by zzarcon** [comment]
Docs added :dancer:

**Comment by aexmachina** [comment]
Awesomez. Thanks!

**Comment by aexmachina** [comment]
Published v4.1.0

**Comment by zzarcon** [comment]
Thanks you for the repo!!

**Pull request merged**
